language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
before_install:
  - pip install codestyle pytest Flask-Testing
script:
  - py.test
before_script:
  - codestyle --statistics --count webapp/
