language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - travis_wait mvn install
before_install:
  - pip install pep8 pytest Flask-Testing
script:
  - py.test -v
after_script:
  - pep8 --statistics --count webapp/
