language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
before_install:
    - pip install pep8
before_script:
  - pep8 --statistics --count --show-pep8 webapp/
